
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Collections.ObjectModel;

namespace YourNamespace {
    using System;
    using Terminal.Gui;
    
    
    public partial class Window1 : Terminal.Gui.Window {
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.TabView tabView;
        
        private Terminal.Gui.ListView listView;
        
        private Terminal.Gui.View view;
        
        private void InitializeComponent() {
            this.view = new Terminal.Gui.View();
            this.listView = new Terminal.Gui.ListView();
            this.tabView = new Terminal.Gui.TabView();
            this.frameView = new Terminal.Gui.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = Pos.Percent(25);
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.Border.BorderStyle = LineStyle.Single;
            this.TextAlignment = Alignment.Start;
            this.Title = "";
            this.frameView.Width = Dim.Percent(20);
            this.frameView.Height = Dim.Fill(0);
            this.frameView.X = 0;
            this.frameView.Y = 0;
            this.frameView.Visible = true;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = LineStyle.Single;
            this.frameView.TextAlignment = Alignment.Start;
            this.frameView.Title = "Main Menu";
            this.Add(this.frameView);
            this.tabView.Width = Dim.Fill(0);
            this.tabView.Height = Dim.Fill(0);
            this.tabView.X = 0;
            this.tabView.Y = 0;
            this.tabView.Visible = true;
            this.tabView.Data = "tabView";
            this.tabView.TextAlignment = Alignment.Start;
            this.tabView.MaxTabTextWidth = 30u;
            this.tabView.Style.ShowBorder = true;
            this.tabView.Style.ShowTopLine = true;
            this.tabView.Style.TabsOnBottom = false;
            Tab tabViewplan;
            tabViewplan = new Tab()
            {
                DisplayText = "Plan",
                View = new View()
            };
            tabViewplan.View.Width = Dim.Fill();
            tabViewplan.View.Height = Dim.Fill();
            this.listView.Width = Dim.Fill(0);
            this.listView.Height = Dim.Fill(0);
            this.listView.X = 0;
            this.listView.Y = 0;
            this.listView.Visible = true;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Alignment.Start;
            this.listView.Source = new ListWrapper<string>(new ObservableCollection<string>() {
                        "Overview",
                        "Crew",
                        "NOTAMs",
                        "Origin",
                        "Destination",
                        "Alternate",
                        "Weight & Cargo",
                        "Radio"});
            this.listView.AllowsMarking = false;
            this.listView.AllowsMultipleSelection = true;
            tabViewplan.View.Add(this.listView);
            tabView.AddTab(tabViewplan, false);
            Tab tabViewchecklist;
            tabViewchecklist = new Tab() 
            {
                DisplayText = "Checklist",
                View = new View()
            };
            
            tabViewchecklist.View.Width = Dim.Fill();
            tabViewchecklist.View.Height = Dim.Fill();
            tabView.AddTab(tabViewchecklist, false);
            this.tabView.ApplyStyleChanges();
            this.frameView.Add(this.tabView);
            this.view.Width = Dim.Fill(0);
            this.view.Height = Dim.Fill(0);
            this.view.X = Pos.Percent(20);
            this.view.Y = 0;
            this.view.Visible = true;
            this.view.Data = "view";
            this.view.TextAlignment = Alignment.Start;
            this.Add(this.view);
        }
    }
}
